name: Build React on S3(develop)
on:
  push:
      branches:
        - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main  # リポジトリをチェックアウト

      - name: Prepare .env file
        run: |
          echo "TEST"
          echo "TEST2"
          echo `aws ssm get-parameter --name /github/wat-notes3/dev --output json`
          echo "TEST3"
          echo `aws ssm get-parameter --name /github/wat-notes3/dev --output json | jq -r .Parameter`
          echo "TEST4"
          echo `aws ssm get-parameter --name /github/wat-notes3/dev --output json | jq -r .Parameter.Value`
          echo "TEST5"
          aws ssm get-parameter --name /github/wat-notes3/dev --output json | jq -r .Parameter.Value > .env
          echo "TEST5.5"
          cat .env
          echo "TEST6"
          aws ssm get-parameter --name /github/wat-notes3/dev --output json | jq -r .Parameter.Value >> "$GITHUB_ENV"
          ls -la
          cat .env >> $GITHUB_ENV
          echo "TEST7"
          echo ${{ env.TEST }}
          echo ${{ env.NEXT_PUBLIC_TEST }}

      - name: echo env
        run: |
          VALUE=`aws ssm get-parameter --name /github/wat-notes3/dev --output json | jq -r .Parameter.Value`
          echo "${{ env.VALUE }}"
          toJSON(`aws ssm get-parameter --name /github/wat-notes3/dev --output json | jq -r .Parameter.Value`)

      - name: Install Dependencies
        run: npm install

      - name: Build and Export
        run: npm run export

      - name: Deploy  # S3にデプロイ 
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_DEVELOP }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEVELOP }}
        run: 
          aws s3 sync --region ap-northeast-1 ./out s3://wat-note3-develop --delete
