name: Build React on S3(prd)
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main # リポジトリをチェックアウト

      - name: "set aws credential"
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Prepare .env file
        run: |
          aws ssm get-parameter --name /github/wat-notes3 --output json | jq -r .Parameter.Value > .env
          cut -d= -f2 .env  | xargs -I arg echo ::add-mask::arg
          cat .env >> "$GITHUB_ENV"

      - name: Install Dependencies
        run: npm install

      - name: Build and Export
        run: npm run build

      - name: Deploy # S3にデプロイ
        run: aws s3 sync --region ap-northeast-1 ./out s3://prd-wat-note3-bucket --delete

      - name: Send Data to algolia # Algoliaにデータ送信
        run: cd tools/algolia && node sendRecords.js

      # Cloudfront キャッシュ削除
      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id $CLOUDFRONT_DISTRIBUTION_ID \
            --paths "/*"
