name: Build React on S3
on:
  push:
      branches:
        - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main  # リポジトリをチェックアウト

      - name: "set aws credential"
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Prepare .env file
        run: |
          aws ssm get-parameter --name /github/wat-notes3 --output json | jq -r .Parameter.Value > .env
          cat .env >> "$GITHUB_ENV"

      - name: Install Dependencies
        run: npm install

      - name: Build and Export
        run: npm run export

      - name: Deploy  # S3にデプロイ 
        run: 
          aws s3 sync --region ap-northeast-1 ./out s3://wat-note3 --delete
